# Generated by Django 2.2.4 on 2019-08-30 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('pos_x', models.FloatField(help_text='Position on length axis', null=True)),
                ('pos_y', models.FloatField(help_text='Postiion on width axis', null=True)),
                ('player_num', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('dim_x', models.FloatField(help_text='Playing field length')),
                ('dim_y', models.FloatField(help_text='Playing field width')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_goals', models.PositiveSmallIntegerField(default=0)),
                ('visiting_goals', models.PositiveSmallIntegerField(default=0)),
                ('datetime', models.DateTimeField(null=True)),
                ('actions', models.ManyToManyField(to='games.Action')),
                ('local_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_club', to='games.Club')),
                ('visiting_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiting_club', to='games.Club')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Club'),
        ),
        migrations.AddField(
            model_name='action',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Player'),
        ),
    ]
